name: Demo Workflow

on:
  workflow_dispatch:  # lets you run it manually
  schedule:
    - cron: "0 * * * *"  # runs every hour

jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, your first GitHub Action is live!"
