name: Update NSG RDP Rule

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=terraform/nsg-rule init

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform/nsg-rule plan \
            -var="my_public_ip=${{ secrets.MY_PUBLIC_IP }}"

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform/nsg-rule apply -auto-approve \
            -var="my_public_ip=${{ secrets.MY_PUBLIC_IP }}"
